"""user tokens

Revision ID: 674441722c0c
Revises: a6918c5408cf
Create Date: 2021-08-22 14:08:05.046062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674441722c0c'
down_revision = 'a6918c5408cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
